### PR TITLE
Awesome books: a complete website with navigation

### PR DESCRIPTION
**Pull request by Allenkeys**
### Project requirements

- Modify the Awesome books application to have:
  - A Navigation bar.
  - Three content sections:
    1. Books list.
    2. Add book form.
    3. Contact info.
- Use this wireframe as a guide
- Make sure that when you click on any of the links, the main area changes to display only one of the three content sections. (Hint: you can simply add and remove CSS classes to display or hide the content.)
- To change the contents of the page, don't use any library or framework, use only plain JavaScript and CSS.

### CODE REVIEW

**Review by andersonlebon — CHANGES_REQUESTED** [review]
### Hi @Allenkeys and @Rikol137  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :stop_sign: 

- [ ]  You have submitted a project, that doesn't have linters.
Screenshot from 2022-10-27 19-31-54


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Allenkeys** [comment]
@andersonlebon Thank you for your time.
My project has linters but I get this messages on the terminal when I run `npx eslint .`

`TypeError: Cannot read property 'value' of null
Occurred while linting /home/josh/Desktop/microverse/module2/awesome-books/main.js:33
    at checkSpacingBefore (/home/josh/Desktop/microverse/module2/awesome-books/node_modules/eslint/lib/rules/template-curly-spacing.js:52:24)
    at TemplateElement (/home/josh/Desktop/microverse/module2/awesome-books/node_modules/eslint/lib/rules/template-curly-spacing.js:136:17)
    at /home/josh/Desktop/microverse/module2/awesome-books/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/josh/Desktop/microverse/module2/awesome-books/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/josh/Desktop/microverse/module2/awesome-books/node_modules/eslint/lib/linter/node-event-generator.js:293:26)
    at NodeEventGenerator.applySelectors (/home/josh/Desktop/microverse/module2/awesome-books/node_modules/eslint/lib/linter/node-event-generator.js:322:22)
    at NodeEventGenerator.enterNode (/home/josh/Desktop/microverse/module2/awesome-books/node_modules/eslint/lib/linter/node-event-generator.js:336:14)
    at CodePathAnalyzer.enterNode (/home/josh/Desktop/microverse/module2/awesome-books/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/josh/Desktop/microverse/module2/awesome-books/node_modules/eslint/lib/linter/linter.js:960:32`

**Comment by Allenkeys** [comment]
@andersonlebon  I would appreciate if you could help, just if you've had such problems before. I think my code at line 33 prevents parse by linters. You know if there's something I could do about that line of code.

**Comment by andersonlebon** [comment]
Hey @Allenkeys

**Comment by Allenkeys** [comment]
@andersonlebon Hello

**Comment by andersonlebon** [comment]
Did you fix your issue?

**Comment by rloterh** [comment]
Hi @Allenkeys 
In order to fix your linters to work with GitHub actions, you can follow the steps below:
- Remove the `node_modules` directory
- Remove installed linter configuration files and directories
- Reinstall linters following this [recommended link](https://github.com/microverseinc/linters-config/tree/master/javascript)
- run `npm i` to install other node packages
- Fix linter errors showing in your code editor, if any,
- Commit changes and push

**Comment by Allenkeys** [comment]
@andersonlebon I have fixed it, but the github Action is not responding here. But linters works perfectly fine locally.

**Review by rloterh — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, whereby linter checks not showing on your Pull Request. Kindly ensure that linters are properly configured with GitHub actions **all** required linters are properly configured, and checks are passing. Kindly request for another code review when this is done.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rloterh** [comment]
@Allenkeys 
Kindly check how to troubleshoot GitHub action via [this link](https://github.com/microverseinc/linters-config#troubleshooting)
Cheers! 😃

**Comment by Allenkeys** [comment]
@rloterh when I run `npm install --save-dev hint@7.x` the installation stops halfway. Is there a way I can fix this?

**Comment by Allenkeys** [comment]
@rloterh I get this on my terminal:
`npm WARN deprecated @types/keyv@4.2.0: This is a stub types definition. keyv provides its own type definitions, so you do not need this installed.

> canvas@2.10.1 install /home/josh/Desktop/microverse/module2/awesome-books/node_modules/canvas
> node-pre-gyp install --fallback-to-build --update-binary
`
And it hangs that way forever.

**Comment by rloterh** [comment]
Hi @Allenkeys 
Can you kindly send me screenshots of the error via slack?
It's probably you missed some step(s) in the above. If old installation files are properly cleared, and a fresh installation is done, I believe you should not have those errors you just mentioned.
I'll urge you to also do some googling on the error, to find a way around it. 

Don't give up, every developer faces this journey! Cheers! 😃

**Comment by Allenkeys** [comment]
I've sent you a message on slack already. I've upgraded my npm to lts, still hanging. @rloterh

**Comment by rloterh** [comment]
Hi @Allenkeys 
I see the issue to be emerging from Github actions. Kindly follow the later discussion we had on zoom

**Review by KayLemba — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hello    @Team    , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- [x] Your project is professional 

- [x]  Your repo is professional 

- [x]  Neat UI Design 




 

- [x] No Linter Errors






Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

well-1

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
